package com.example.pdf_generator.dto;

import lombok.Data;

import java.util.List;

/**
 * Data Transfer Object (DTO) for representing the data required to generate a PDF.
 */
@Data
public class PdfRequestDTO {

    private String seller;          // Name of the seller
    private String sellerGstin;     // GSTIN of the seller
    private String sellerAddress;    // Address of the seller
    private String buyer;           // Name of the buyer
    private String buyerGstin;      // GSTIN of the buyer
    private String buyerAddress;     // Address of the buyer
    private List<ItemDTO> items;    // List of items included in the PDF

    /**
     * Inner class representing an item in the PDF.
     */
    @Data
    public static class ItemDTO {
        private String name;
        private String quantity;
        private Double rate;
        private Double amount;

        // Getters and setters are automatically generated by Lombok's @Data annotation
    }

    // Getters and setters for PdfRequestDTO are automatically generated by Lombok's @Data annotation
}
